### ISSUE TITLE
mark broken sequences in the table

### ISSUE THREAD

**Issue by ChristianBeer** [dubslow/MersenneForumAliquot#1]
I recently reserved a broken sequence (without knowing it is broken) and just recognized at the upload of the result that all indexes where already in factordb.

Could you please mark those brocken sequences in the table somehow? Maybe the easiest way would be to permanently reserve them with a message like "broken in factorDB" so everyone who uses your table as a means to select which sequence to increase is at least warned about it.

**Comment by dubslow** [comment]
I hadn't marked this closed because the formatting is currently awful :smile:
